config/routes.rb
Rails.application.routes.draw do
  resources :users

  get 'locations/start'

  get '/tour/:id', to: 'locations#map', as: 'location'
  get '/tour_stop/:id', to: 'locations#info', as:'tour_stop'
 
  get 'tour' => 'locations#menu'
  get 'start_tour' => 'locations#start'

  get '/highlights', to: "highlights#show"

  root to: "home#show" 
  # get '/webcam', to: "webcam#show"

  get "/webcam", to: "pages#show"
  get "/kups", to: "pages#show"
  get "/social_media", to: "pages#show"
  get "/overnight_form", to: "pages#show"
  get "/cafe", to: "pages#show"
  get "/overnight_error", to: "pages#show"
  get "/overnight_success", to: "pages#show"
end

app/models/location.rb
class Location < ActiveRecord::Base
  serialize :pictures, Array
#source:
#http://stackoverflow.com/questions/7394088/rails-get-next-previous-record

  def next
    Location.where("id > ?", self.id).order("id ASC").first || Location.first
  end

  def previous
    Location.where("id < ?", self.id).order("id DESC").first || Location.last
  end
 
end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::Validations

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :name, :presence => true, :length => { :maximum => 30 }
  validates :date, :presence => true, :format => /(0[1-9]|1[012])[- \/.](0[1-9]|[12][0-9]|3[01])[- \/.]\d\d/
  validates :phone, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
  layout "page"
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "application"
  def show
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  layout "page"
  
  respond_to :json
  #information on the current location
  def info
    session[:prev_cur] = session[:previous]
    @location = Location.find(params[:id])
    session[:previous] = @location.id
  end
  
  #menu view
  def menu
    session[:previous] = session[:prev_cur]
    @locations = Location.all
  end

  #if the user comes to the site from the 
  #main menu
  def start
    session.clear
    session[:visited] = []
    redirect_to tour_path
  end
  
  #shows current location on map
  def map
    
    @location = Location.find(params[:id])
    
    #If we have a previous location, draw a path from it.
    if session[:previous] == nil
      @previous_location = nil
    else
      @previous_location = Location.find(session[:previous].to_s.to_sym)
    end

    @visited_locations = []
    
    
    session[:visited].each do |i|
      @visited_locations << i
    end

    
    if @previous_location != nil and !session[:visited].include?(@previous_location.id)
        session[:visited] << @previous_location.id.to_i - 1 #minus 1 because databases start at 1 but arrays start at 0
    end
    
    #store the previous 
    session[:prev_cur] = session[:previous]
    session[:previous] = @location.id
    
    @all_locations = Location.all
    
    #session.clear
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout "page"
  def show
    render ["pages", request.path].join
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ActiveModel::Validations

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        Overnight.overnight_email(@user).deliver

	format.html { redirect_to overnight_success_url, notice: 'User was successfully created.' }
	format.json { render :show, status: :created, location: @user }
      else
	format.html { redirect_to overnight_error_url}
	format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :date, :phone)
    end
end

app/controllers/webcam_controller.rb
class WebcamController < ApplicationController
  layout "page"
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/webcam_helper.rb
module WebcamHelper
end

app/views/highlights/show.html.erb
<html>


<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
  <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
  <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
  <title>Puget Sound Experience</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>



<div class = "test">
  <div class="target">

    <div class="roller-item" style = "background-image: url('https://beerandhotdogs.files.wordpress.com/2013/07/20130723-072227.jpg');">
      <div class = "bottom-half">
        <h3>The Red Hot </h3> 
        An over-21 spot for creative hot dogs plus ample rotating craft beers.
        <br>
        Distance: 0.6 Miles 
          <br>
          <a href="https://redhottacoma.com" class = 'btn btn-default btn-lg'>Website</a>
          <br>
      </div>  
    </div>


    <div class="roller-item" style = "background-image: url('http://museumofglass.org/view.image?Id=910');">
      <div class = "bottom-half">
        <h3>Tacoma Museum of Glass</h3> 
        A 75,000-square-foot art museum dedicated to the medium of glass.
        <br>
        Distance: 4.2 Miles 
          <br>
          <a href="http://museumofglass.org/" class = 'btn btn-default btn-lg'>Website</a>
          <br>
      </div>  
    </div>


    <div class="roller-item" style = "background-image: url('http://3.bp.blogspot.com/-yuxKUrKVvsQ/TdX8u_fFYPI/AAAAAAAAAD0/GhOpKWZ0bbI/s400/thai.jpg');">
      <div class = "bottom-half">
        <h3>Silk Thai Cafe</h3> 
        Thai eatery decked out with Siamese artifacts, offering a lineup of standards & specialties.
        <br>
        Distance: 0.6 Miles 
          <br>
          <a href="www.silkthaicafe.com/" class = 'btn btn-default btn-lg'>Website</a>
          <br>
      </div>  
    </div>

     <div class="roller-item" style = "background-image: url('http://exit133.com/uploads/Point-Defiance.jpg');">
      <div class = "bottom-half">
        <h3>Point Defiance Park</h3> 
        One of the largest parks in the US, overlooking the beautiful Puget Sound.
        <br>
        Distance: 4.8 Miles 
          <br>
          <a href="www.pdza.org/" class = 'btn btn-default btn-lg'>Website</a>
          <br>
      </div>  
    </div>

     <div class="roller-item" style = "background-image: url('http://www.calautomuseum.org/wp-content/uploads/2014/03/lemay2.jpg');">
      <div class = "bottom-half">
        <h3>LeMay Car Museum</h3> 
        One of the world’s largest auto museums and attractions.
        <br>
        Distance: 4.9 Miles
          <br>
          <a href="www.lemaymuseum.org/" class = 'btn btn-default btn-lg'>Website</a>
          <br>
      </div>  
    </div>

    <div class="roller-item" style = "background-image: url('http://livingpiercecounty.com/wp-content/uploads/2013/04/proctor-tacoma2.jpg');">
      <div class = "bottom-half">
        <h3>Proctor District</h3> 
        A small town "urban village" with shopping, restuarants and entertainment.
        <br>
        Distance: 4.9 Miles 
          <br>
          <a href="http://www.proctordistrict.com/" class = 'btn btn-default btn-lg'>Website</a>
          <br>
      </div>  
    </div>

    <div class="roller-item" style = "background-image: url('http://s3-media2.fl.yelpcdn.com/bphoto/uh3E96liuA0yXsRoZiuOag/348s.jpg');">
      <div class = "bottom-half">
        <h3>Metronome Coffee</h3> 
        Espresso, coffee & tea meet light bites & beer at this hip spot with open-mike nights.
        <br>
        Distance: 0.7 Miles 
          <br>
          <a href="www.metronomecoffee.com/" class = 'btn btn-default btn-lg'>Website</a>
          <br>
      </div>  
    </div>
  </div>


</div>

  </body> 
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>


<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
  <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
  <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
  <title>Puget Sound Experience</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class = "test">


<div id="home-carousel" class="carousel slide carousel-fade" data-ride="carousel">
  <!-- Indicators -->
  
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    
    <div class="item active">
      <img class="carousel-img" src="/images/carousel/schiff.jpg">
      <div class="carousel-caption">
        <h1 class = "title">The Puget Sound <span style = "font-style: italic;">Experience</span></h1>  
        <br>
        <br>
      </div>
    </div>


    <div class="item">
      <img class="carousel-img" src="/images/carousel/op.jpg">
      <div class="carousel-caption">
        <h1 class = "title">The Puget Sound <span style = "font-style: italic;">Experience</span></h1>
        <br>
        <br>
      </div>
    </div>

    <div class="item">
      <img class="carousel-img" src="/images/carousel/howarth.jpg">
      <div class="carousel-caption">
        <h1 class = "title">The Puget Sound <span style = "font-style: italic;">Experience</span></h1>
        <br>
        <br>
      </div>
    </div>

    <div class="item">
      <img class="carousel-img" src="/images/carousel/thompson.jpg">
      <div class="carousel-caption">
        <h1 class = "title">The Puget Sound <span style = "font-style: italic;">Experience</span></h1>
        <br>
        <br>
      </div>
    </div>

  </div>
  
</div>

<nav class="navbar navbar-default" role="navigation">
  <div class="container" >
      <div>
        <%= link_to "", root_path, :id => 'logo-small' %>
      </div>
    <div class="navbar-header"></div>
  </div>
</nav>



<div class="target">

  <div class="roller-item" style = "background-image: url('http://www.pugetsound.edu/files/pages/_DSC1659.jpg');">
    <div class = "bottom-half">
      <h3>Look around campus</h3>
      <%= link_to "Virtual Tour", start_tour_path, :class => 'btn btn-default btn-lg', method: :get %> 
    </div>  
  </div>


  <div class="roller-item" style = "background-image: url('http://3.bp.blogspot.com/-g1ix8vRzcJY/UHcCajdqR2I/AAAAAAAAIsk/KuEU9iIc_EI/s1600/Mount+Rainier+Washington+11.jpg');">
    <div class = "bottom-half">
      <h3>The Pacific Northwest</h3>
      <%= link_to "Visit Rainier", webcam_path, :class => 'btn btn-default btn-lg', method: :get %>
     </div>
  </div>


  <div class="roller-item" style = "background-image: url('http://www.ctcl.org/sites/default/files/pugetsound12.jpg');">
    <div class = "bottom-half">
    <h3>Connect with current students</h3>
        <%= link_to "Campus hangouts", cafe_path, :class => 'btn btn-default btn-lg', method: :get %> 
    </div>
  </div>

  <div class="roller-item" style = "background-image: url('http://www.pugetsound.edu/images/vt/buildings/Wheelock_KUPS.jpg');">
    <div class = "bottom-half">
    <h3>Learn about student-run radio</h3>
        <%= link_to "KUPS Radio", kups_path, :class => 'btn btn-default btn-lg', method: :get %> 
    </div>
  </div>

   <div class="roller-item" style = "background-image: url('http://s3images.coroflot.com/user_files/individual_files/original_274298_4YOI2OmhX8BvcrIs9LziDVRbx.jpg');">
    <div class = "bottom-half">
    <h3>Tacoma Life</h3>
        <%= link_to "Local Highlights", highlights_path, :class => 'btn btn-default btn-lg', method: :get %>
    </div>
  </div>

   <div class="roller-item" style = "background-image: url('http://www2.ups.edu/dcs/dining/OC_2101.jpg');">
    <div class = "bottom-half">
    <h3>Visit our social media</h3>
        <%= link_to "Connect", social_media_path, :class => 'btn btn-default btn-lg', method: :get %>
    </div>
  </div>

   <div class="roller-item" style = "background-image: url('http://blogs.pugetsound.edu/studentlife/files/2011/04/P1050321.jpg');">
    <div class = "bottom-half">
    <h3>Schedule an Overnight</h3>
        <%= link_to "Schedule Now!", overnight_form_path, :class => 'btn btn-default btn-lg', method: :get %>
    </div>
  </div>
</div>


</div>
	

  </body> 
</html>

app/views/layouts/page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    
    <%= javascript_include_tag("https://maps.googleapis.com/maps/api/js?key=AIzaSyCqVNiaRHyWmzfhql0l9qKEUcX7lzWveto") %>
    <%= javascript_include_tag params[:controller], :media => "all" %>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    
    <title>Puget Sound Experience</title>

   <%= stylesheet_link_tag 'locations', media: 'all', 'data-turbolinks-track' => true %>   
   <%= stylesheet_link_tag 'webcam', media: 'all', 'data-turbolinks-track' => true %>

    </script>
  </head>
  <body>


<div class="top-top">
  <!--
  <%= link_to root_path do %>
      <img id="logo" src="/images/logo.gif" />
      <% end %>
      
  <%= link_to "", root_path, :id => 'logo-small2' %> -->
  <div id="logo-small2"></div>
      <div class="dropdown">
	<button class="btn btn-default dropdown-toggle dropdown-button" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
	  Navigation Menu
	  <span class="caret"></span>
	</button>
	<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
	  <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= root_path %>">Home</a></li>
	  <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= tour_path %>">Tour Home</a></li>
	  <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= webcam_path %>">Mt. Rainier</a></li>
	  <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= kups_path %>">KUPS Radio</a></li>
	  <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= social_media_path %>">Social Media</a></li>
	  <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= highlights_path %>">Tacoma Highlights</a></li>
	   <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= overnight_form_path %>">Stay Overnight</a></li>
	  
	</ul>
      </div>
      
      <!--<img id="menu-icon" src="/images/menu_icon.png" /> -->
      
      
    </div>

    <!-- Puget Sound Logo needs to go here -->
    <%= yield %>
    
    <!-- footer needs to go here -->
  </body>
  
</html>

app/views/locations/info.html.erb
  <div class="top-bottom">
    <div class="navigation-arrows">

      <div class="left-arrow">
      <%= link_to location_path(@location) do %>
      
      <img src="/images/left_arrow.png" />
      Previous Location
      
      <% end %>
      </div>
     
      <div class="right-arrow"> 
      <%= link_to location_path(@location.next) do %>
     
        Next Location
        <img src="/images/right_arrow.png" />
     
      <% end %>
      </div>
    </div>
  </div>
  <div class="jumbotron">
  <h1 class="info-title"><%= @location.name %></h1>
   
  <div>     
    <div id='ninja-slider'>
      <ul>
        <% @location.pictures.each do |picture| %>
        <li><div data-image="<%= picture %>"></div></li>
        <% end %>

      </ul>
    </div>
  </div>

  <p><%= @location.long_description %></p>

</div>

app/views/locations/map.html.erb
<div class="top-bottom">
 
  <div class="navigation-arrows">

  <div class="left-arrow"> 
  <%= link_to tour_stop_path(@location.previous) do %>
    <img src="/images/left_arrow.png" />
    Previous Location
  <% end %>
   </div>  
  <div class="right-arrow">
  <%= link_to tour_stop_path(@location), :id => "next-link" do %>
  Next Location
    <img src="/images/right_arrow.png" />

  <% end %>
  </div>
</div>
</div>



<%= content_tag "div", id: "current-location", data: {location:@location} do %>

<% end %>

<%= content_tag "div", id: "all-locations", data: {locations: @all_locations} do %>

<% end %>

<%= content_tag "div", id: "previous-location", data: {previous_location: @previous_location} do %>

<% end %>

<%= content_tag "div", id: "visited-locations", data: {visited_locations: @visited_locations} do %>

<% end %>

<div id="map-canvas"></div>

app/views/locations/menu.html.erb
<div class="top-bottom">
  <div class="navigation-arrows">
   <h3>Choose a Location</h3>
  </div>
  
</div>
<div class="menu">
  

  <% @locations.each do |location| %>
  <%= link_to location_path(location) do %>
  <div class="container menu-item">
    <div class="row">
   <div class="location-picture">
     <div class="col-xs-3">
     <img class="small-pic" src="<%= location.logo_url %>" />
   </div>
   </div>
<div class="col-xs-9">
   <div class="location-info">
    <span class="location-text">
     <p class="location-name"><%= location.name %></p>
    
     <p class="location-desc"><%= location.short_description %></p>
   </span>
   </div>
   </div>
    </div>
   <!--<div class="clear"></div>-->
  </div>

  <% end %>
<% end %>

</div>
 

app/views/overnight/overnight_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>
      <%= @user.name %> would like to schedule an overnight for <%= @user.date %>
    </p>
    <p>
      <%= @user.name %>'s contact info:
      <ul>
        <li> email: <%= @user.email %></li>
        <li> phone: <%= @user.phone %></li>
      </ul>
    </p>
  </body>
</html>

app/views/overnight/overnight_email.text.erb
<%= @user.name %> would like to schedule an overnight for <%= @user.date %>.

<%= @user.name %>'s contact info:
	email: <%= @user.email %>
	phone: <%= @user.phone %>

app/views/pages/cafe.html.erb
<div class="jumbotron">
  <h1>Campus Hangouts</h1>

	<div class = "text">
		<h2>Oppenheimer Café</h2>
		Oppenheimer Café is located in the newly updated science quad formed by Harned and Thompson Halls. The cafe is staffed by university students in conjunction with University of Puget Sound Dining and Conferences Services. The Oppenheimer Café provides an open environment for students and staff to meet, grab a cup of coffee, get a bite to eat and study. The OC uses Caffé Vita as coffee roaster and provider. This relationship is treasured since Caffé Vita is well equipped to meet the demands of our business, training and product knowledge. <a href = "http://www.pugetsound.edu/about/offices-services/dining-conference-services/oppenheimer-cafe-oc/">Click here</a> for more information about Oppenheimer Café.
	</div>

	<img src="http://livingpiercecounty.com/wp-content/uploads/2014/08/DSC_0081.jpg" alt="Mountain View" class="webcam image">

	<div class = "text">
		<h2>Diversions Café</h2>
		Diversions Café is a great meeting spot for students to study or socialize over a delicious coffee, tea, or smoothie. The café acts as a social hot-spot on campus and provides a great opportunity become acquainted with the student body. Diversions itself is located on the main floor of the Wheelock Student Center, and was established in the fall of 1997. <a href = "http://www.pugetsound.edu/about/offices-services/dining-conference-services/oppenheimer-cafe-oc/">Click here</a> for more information about Diversions.
	</div>
	<img src="http://www.pugetsound.edu/images/vt/buildings/WheelockDiversionsTD022.jpg" alt="Mountain View" class="webcam image">

	<div class = "text">
		<h2>The Cellar</h2>
		The Cellar is located in the basement of Wheelock Student Center, and offers an entirely student-run dining experience. Check out our menu for all of our ingredients and specials, or tour the C-Store for all of your snacking needs. Concerned gluten-free and vegan eaters need not worry, the Cellar offers options for all dietary concerns! The Cellar has remained a campus tradition dating back as far as 1976, and has undergone numerous changes since then.  Once named Cellar “X,” this restaurant began as a sandwich shop for students before it quickly was contracted to the Antique Sandwich Company (located on Pearl Street) for a year in order to make necessary improvements on food quality. <a href = "http://www.pugetsound.edu/about/offices-services/dining-conference-services/the-cellar/">Click here</a> for more information about The Cellar.

	</div>

	<img src="http://www.pugetsound.edu/images/vt/buildings/Wheelock_Celler.jpg" alt="Mountain View" class="webcam image">



</div>

app/views/pages/overnight_error.html.erb
<div class="jumbotron">
<p>Sorry we could not process your request. Please make sure you have filled out each field appropriately.</p>

<%= link_to 'Back', overnight_form_path %>
</div>

app/views/pages/overnight_form.html.erb
<div class="jumbotron">
<h1>Schedule an Overnight</h1>

<%= form_for User.new do |f| %>
  <p>
    Name (first and last):
  </p>
  <p>
    <%= f.text_field :name %>
  </p>
  <p>
    Email:
  </p>
  <p>
    <%= f.text_field :email %>
  </p>
  <p>
    Phone Number
  </p>
  <p>
    <%= f.text_field :phone %>
  </p>
  <p>
    Desired Date for Overnight (MM/DD/YYYY)
  </p>
  <p>
    <%= f.text_field :date %>
  </p>
  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>
</div>

app/views/pages/overnight_success.html.erb
<div class="jumbotron">

<p>An advisor has been notified of your request.</p>

<%= link_to 'Back to Home', root_path %>

</div>

app/views/pages/social_media.html.erb
<!--Twitter-->
<div class="jumbotron">
<a class="twitter-timeline" href="https://twitter.com/univpugetsound" data-widget-id="536979543567761408">Tweets by @univpugetsound</a>
<script>
  !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
</script>

<!--Facebook-->

<h3> Like us on Facebook! </h3>

<div id="fb-root"></div>
<script>
  (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

<div class="fb-like" data-href="https://www.facebook.com/univpugetsound" data-width="500" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>

<!--Instagram-->

<h3> Follow us on Instagram! </h3>

<!-- SnapWidget -->
<iframe src="http://snapwidget.com/sc/?u=dW5pdnB1Z2V0c291bmR8aW58MTUwfDN8M3x8eWVzfDIwfG5vbmV8b25TdGFydHx5ZXN8bm8=&ve=031214" title="Instagram Widget" class="snapwidget-widget" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:500px; height:150px"></iframe>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Date</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.date %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Date:</strong>
  <%= @user.date %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>